### PR TITLE
Create sarthakvermaa.txt

### PR DESCRIPTION
**Pull request by sarthakvermaa**
Issue: #113

### CODE REVIEW

**Comment by AyushmanSoni** [comment]
also place the given screen beside your design so that I can compare both

**Comment by AyushmanSoni** [comment]
comments added in your figma file

**Comment by AyushmanSoni** [comment]
apply changes in your file till 5pm

**Comment by sarthakvermaa** [comment]
@AyushmanSoni Changes made on the file.

**Pull request merged**
