### PR TITLE
Dynamic island animation task done

### PR DESCRIPTION
**Pull request by ajay484**
Issue: #49

### CODE REVIEW

**Comment by AyushmanSoni** [comment]
@ajay484  correct the size of your dynamic island while open and also while it is closed. there is unequal gap between dynamic island's top and both sides with screen. Also it is bigger than that is required when it is closed.

**Comment by ajay484** [comment]
@AyushmanSoni i have done some changes  please check

**Comment by AyushmanSoni** [comment]
send your figma file where you have worked.

**Comment by ajay484** [comment]
@AyushmanSoni 
https://www.figma.com/file/Ke7X96AhVKk1xJugyfsURj/Dynamic-island?type=design&node-id=7%3A406&mode=design&t=LSuXAcSRGiHklPEa-1

**Comment by AyushmanSoni** [comment]
resend pull request

**Pull request merged**
